replicaCount: 1

containers:
  image: 134448505602.dkr.ecr.ap-south-1.amazonaws.com/dev/eos-registry-api
  port: 8761

labels:
  app: eos-registry-api
  env: dev

metadata:
  namespace: eos-dev

resources:
  requests:
    cpu: 125m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi
